### ISSUE TITLE
Overwriting system defined compilers

### ISSUE THREAD

**Issue by Irubataru** [aostruszka/nonrec-make#16]
Not sure if it is intentional or not, but maybe you shouldn't overwrite the CC and CXX variables in the "config-default.mk", so rather than

```make
CC := gcc
CXX := g++
```

have 

```make
CC ?= gcc
CXX ?= g++
```

At least it took me some time to figure out that the compiler had been overwritten because of the pretty printing.

**Comment by aostruszka** [comment]
I've just found out that I have not yet pushed fix for that :) - it is now in 40e0033d3119c80eebe90a23d62e439edcf16fa7
