### ISSUE TITLE
Bug in the config-default.mk file

### ISSUE THREAD

**Issue by pilpil-qphy** [aostruszka/nonrec-make#26]
The below code from "config-default.mk" file is buggy.

ifeq ($(origin $(CC)),default)
  CC := gcc
endif

It should rather be (no $( ) around the CC), like as,

ifeq ($(origin CC),default)
  CC := gcc
endif

**Comment by aostruszka** [comment]
Thank you!  Fixed with 15efeacbe11ff4e0441fa3568780c4ca24190407
Don't know why I used it that way - in the same file at bottom I used 'origin' correctly for RANLIB, must have been tired that day :-).
